"""add missing columns to vocab_words

Revision ID: 3608e482873d
Revises: 955b4a1a29af
Create Date: 2026-04-29 14:00:07.981009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3608e482873d'
down_revision: Union[str, Sequence[str], None] = '955b4a1a29af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocab_words', sa.Column('difficulty', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocab_words', 'difficulty')
    # ### end Alembic commands ###
