"""add va tables

Revision ID: 6c2a81fc706b
Revises: 241c34ed57af
Create Date: 2026-03-16 23:31:16.252103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c2a81fc706b'
down_revision: Union[str, Sequence[str], None] = '241c34ed57af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('va_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct', sa.String(length=5), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('strategy', sa.JSON(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_va_questions_id'), 'va_questions', ['id'], unique=False)
    op.create_table('va_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('selected', sa.String(length=5), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['va_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('va_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pj_attempted', sa.Integer(), nullable=True),
    sa.Column('pj_correct', sa.Integer(), nullable=True),
    sa.Column('ooo_attempted', sa.Integer(), nullable=True),
    sa.Column('ooo_correct', sa.Integer(), nullable=True),
    sa.Column('ps_attempted', sa.Integer(), nullable=True),
    sa.Column('ps_correct', sa.Integer(), nullable=True),
    sa.Column('total_attempted', sa.Integer(), nullable=True),
    sa.Column('total_correct', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('va_progress')
    op.drop_table('va_attempts')
    op.drop_index(op.f('ix_va_questions_id'), table_name='va_questions')
    op.drop_table('va_questions')
    # ### end Alembic commands ###
