"""add target_exam target_year streak to users

Revision ID: 955b4a1a29af
Revises: b4e4c8ae9f8f
Create Date: 2026-03-25 17:33:41.507258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '955b4a1a29af'
down_revision: Union[str, Sequence[str], None] = 'b4e4c8ae9f8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('target_exam', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('target_year', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('current_streak', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_streak')
    op.drop_column('users', 'target_year')
    op.drop_column('users', 'target_exam')
    # ### end Alembic commands ###
