"""add sentences to va_questions

Revision ID: 9d2df7ef69bb
Revises: 3cbc200162e4
Create Date: 2026-03-22 21:27:30.305124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2df7ef69bb'
down_revision: Union[str, Sequence[str], None] = '3cbc200162e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('va_questions', sa.Column('sentences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('va_questions', 'sentences')
    # ### end Alembic commands ###
