"""add mockportal tables

Revision ID: b4e4c8ae9f8f
Revises: 9d2df7ef69bb
Create Date: 2026-03-25 10:19:46.460379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e4c8ae9f8f'
down_revision: Union[str, Sequence[str], None] = '9d2df7ef69bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('full', 'half', 'topic', name='mocktype'), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('badge', sa.Enum('hot', 'new', 'locked', name='badgetype'), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficultylevel'), nullable=True),
    sa.Column('total_duration', sa.String(length=30), nullable=True),
    sa.Column('duration_secs', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_tests_id'), 'mock_tests', ['id'], unique=False)
    op.create_table('marking_schemes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mock_id', sa.UUID(), nullable=False),
    sa.Column('correct_marks', sa.Integer(), nullable=True),
    sa.Column('incorrect_marks', sa.Integer(), nullable=True),
    sa.Column('tita_marks', sa.Integer(), nullable=True),
    sa.Column('correct_sub', sa.String(length=100), nullable=True),
    sa.Column('wrong_sub', sa.String(length=100), nullable=True),
    sa.Column('tita_sub', sa.String(length=100), nullable=True),
    sa.Column('has_tita', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mock_id'], ['mock_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mock_id')
    )
    op.create_table('mock_instructions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mock_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mock_id'], ['mock_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mock_id', sa.UUID(), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mock_id'], ['mock_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mock_id', sa.UUID(), nullable=False),
    sa.Column('section_key', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('duration_secs', sa.Integer(), nullable=True),
    sa.Column('questions', sa.Integer(), nullable=True),
    sa.Column('breakdown', sa.String(length=200), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mock_id'], ['mock_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_syllabus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mock_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('covered', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mock_id'], ['mock_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mock_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'submitted', 'timed_out', name='attemptstatus'), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_taken_secs', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.Column('wrong', sa.Integer(), nullable=True),
    sa.Column('unattempted', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('section_breakdown', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mock_id'], ['mock_tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_attempts_id'), 'test_attempts', ['id'], unique=False)
    op.create_table('passages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('passage_key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['mock_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passages_id'), 'passages', ['id'], unique=False)
    op.create_table('mock_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('passage_id', sa.UUID(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('mcq', 'tita', 'para_jumble', 'para_summary', 'odd_one_out', name='questiontype'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_option', sa.Integer(), nullable=True),
    sa.Column('correct_answer', sa.String(length=200), nullable=True),
    sa.Column('hint', sa.String(length=200), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('key_point', sa.String(length=500), nullable=True),
    sa.Column('marks_correct', sa.Integer(), nullable=True),
    sa.Column('marks_incorrect', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['mock_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_questions_id'), 'mock_questions', ['id'], unique=False)
    op.create_table('question_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('not_visited', 'visited_not_answered', 'answered', 'marked_review', 'answered_marked', name='questionstatus'), nullable=True),
    sa.Column('selected', sa.Integer(), nullable=True),
    sa.Column('tita_answer', sa.String(length=200), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('time_spent_secs', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['mock_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_responses')
    op.drop_index(op.f('ix_mock_questions_id'), table_name='mock_questions')
    op.drop_table('mock_questions')
    op.drop_index(op.f('ix_passages_id'), table_name='passages')
    op.drop_table('passages')
    op.drop_index(op.f('ix_test_attempts_id'), table_name='test_attempts')
    op.drop_table('test_attempts')
    op.drop_table('mock_syllabus')
    op.drop_table('mock_sections')
    op.drop_table('mock_rules')
    op.drop_table('mock_instructions')
    op.drop_table('marking_schemes')
    op.drop_index(op.f('ix_mock_tests_id'), table_name='mock_tests')
    op.drop_table('mock_tests')
    # ### end Alembic commands ###
